site_name: Django使用指南

nav:
- Django框架入门: Django框架入门.md
- Django核心知识点详解: 
  - 01 中间件: Django核心/中间件.md
- Django中常用的组件介绍:
  - contenttypes组件: Django组件/Django中contenttypes组件的使用.md
- Django进阶:
  - ORM语句的优化: Django进阶/ORM语句的优化.md
- DRF相关:
  - 认证、权限及访问频率限制简介: DRF相关/认证、权限及访问频率限制.md

theme: readthedocs
